[project]
name = "digital-twin-bbva"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "delta-spark==4.3.0",
    "duckdb>=1.5.4",
    "faker>=40.31.0",
    "jupyter>=1.1.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "psycopg2-binary>=2.9.12",
    "pyspark==4.1.1",
    "sqlalchemy>=2.0.51",
]
